apiVersion: apps/v1
kind: Deployment
metadata:
    name: stats-api
spec:
    replicas: 1
    selector: 
        matchLabels:
            app: stats-api-pod
    template: 
        metadata: 
            labels: 
                app: stats-api-pod
        spec: 
            containers: 
            - name: api
              image: stats:latest
              imagePullPolicy: IfNotPresent
              ports: 
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: stats-api-service # For any communication with this service, this name should be used instead of ip/url/localhost
spec:
    type: ClusterIP
    selector: 
        app: stats-api-pod
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080